version: '3.9'

services:
  sophronia:
    container_name: sophronia
    build: src/sophronia
    env_file:
      - ./.env
    command: npm start
    volumes:
      - ./src/sophronia/:/app
    ports:
      - 3000:3000
    depends_on:
      - berenice
  berenice:
    container_name: berenice
    build: src/berenice
    env_file:
      - ./.env
    environment:
      - FLASK_APP=ukbo:create_app('dev')
    command: flask --debug run --host=0.0.0.0
    volumes:
      - ./src/berenice/:/app
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
