version: "3.9"

services:
  web:
    build: src
    image: "${WEB_IMAGE}"
    env_file:
      - ./.env
    command: flask run --host=0.0.0.0
    ports:
      - "5000:5000"
  nginx:
    build:
      context: ./nginx
      cache_from:
        - "${NGINX_IMAGE}"
    image: "${NGINX_IMAGE}"
    ports:
      - 1337:80
    depends_on:
      - web
