version: "3.9"

services:
  web:
    build: src
    image: "${WEB_IMAGE}"
    env_file:
      - ./.env
    command: flask run --host=0.0.0.0
    ports:
      - "5000:5000"
  nginx:
    image: "${NGINX_IMAGE}"
    build: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
