version: "3.9"

services:
  sophronia:
    container_name: sophronia
    build: src/sophronia
    env_file:
      - ./.env
    command: npm start
    volumes:
      - ./src/sophronia/:/app
    ports:
      - 3000:3000
    depends_on:
      - berenice
  berenice:
    container_name: berenice
    build: src/berenice
    env_file:
      - ./.env
    environment:
      - FLASK_APP=ukbo:create_app('dev')
    command: flask run --host=0.0.0.0
    volumes:
      - ./src/berenice/:/app
    ports:
      - 5000:5000
    depends_on:
      - db
      - elastic
  db:
    container_name: postgres
    image: postgres
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  elastic:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200


volumes:
  elastic_data:
  postgres_data:
