version: "3.9"

services:
  nginx:
    container_name: nginx
    image: "${NGINX_IMAGE}"
    restart: always
    # build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
    networks:
      - deploy-network
  db:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - deploy-network
  elastic:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    restart: always
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - deploy-network
  web:
    container_name: web
    image: "${WEB_IMAGE}"
    # restart: always
    # build: app
    env_file:
      - ./.env
    command: gunicorn --preload --bind 0.0.0.0:5000 "app:create_app()"
    volumes:
      - .:/app
    expose:
      - 5000
    depends_on:
      - db
      - elastic
    networks:
      - deploy-network


volumes:
  elastic_data:
  postgres_data:


networks:
  deploy-network:
    driver: bridge
