version: '3.9'

services:
  frontend:
    container_name: frontend
    build: src/frontend
    env_file:
      - ./.env
    command: npm run dev
    volumes:
      - ./src/frontend/:/app
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    container_name: backend
    build: src/backend
    env_file:
      - ./.env
    environment:
      - FLASK_APP=ukbo:create_app('dev')
    command: flask --debug run --host=0.0.0.0
    volumes:
      - ./src/backend/:/app
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
