version: "3.9"

services:
  web:
      image: "${WEB_IMAGE}"
      build:
        context: ./src/
      env_file:
        - ./.env
      command: gunicorn --preload --bind 0.0.0.0:5000 "ukbo:create_app()"
      volumes:
        - ".:/ukbo/ukbo"
        - "./data:/app/data/"
      expose:
        - 5000
      depends_on:
        - db
        - elastic
      networks:
        - deploy-network
  nginx:
    image: "${NGINX_IMAGE}"
    # build: ./nginx
    restart: always
    ports:
      - 1337:80
    depends_on:
      - web
    networks:
      - deploy-network
  db:
    image: postgres
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - deploy-network
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    restart: always
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - deploy-network


volumes:
  elastic_data:
  postgres_data:
  ukbo:


networks:
  deploy-network:
    driver: bridge
