version: "3.9"

services:
  nginx:
    build:
      context: ./nginx
      cache_from:
        - "${NGINX_IMAGE}"
    image: "${NGINX_IMAGE}"
    ports:
      - 1337:80
    depends_on:
      - web
    networks:
      - deploy-network
  web:
    # build: app
    build:
      context: ./app
    #   cache_from:
    #     - "${WEB_IMAGE}"
    image: "${WEB_IMAGE}"
    env_file:
      - ./.env
    command: flask run --host=0.0.0.0
    volumes:
      - "./:app/app"
    ports:
      - "5000:5000"
    networks:
      - deploy-network

volumes:
  elastic_data:
  postgres_data:


networks:
  deploy-network:
    driver: bridge
