"""Add admissions.

Revision ID: 186fbac8841e
Revises: b03da1e180a0
Create Date: 2022-12-17 18:33:05.429714

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "186fbac8841e"
down_revision = "b03da1e180a0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("week", sa.Column("admissions", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("week", "admissions")
    # ### end Alembic commands ###
