"""Film distributor null.

Revision ID: 3e1d353cf71e
Revises: caeb30be6bad
Create Date: 2023-04-15 20:28:49.281308

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3e1d353cf71e"
down_revision = "caeb30be6bad"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "film", "distributor_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "film", "distributor_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
