"""Add event

Revision ID: b44f4ad55fe0
Revises: 186fbac8841e
Create Date: 2023-02-12 19:22:09.831617

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b44f4ad55fe0"
down_revision = "186fbac8841e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column(
            "area",
            sa.Enum("ETL", "Forecast", "Archive", name="area"),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column(
            "state",
            sa.Enum("Success", "Warning", "Failure", name="state"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event")
    # ### end Alembic commands ###
