"""Add event

Revision ID: caeb30be6bad
Revises: 186fbac8841e
Create Date: 2023-02-14 22:51:28.180780

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "caeb30be6bad"
down_revision = "186fbac8841e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("area", sa.String(length=160), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column(
            "state",
            sa.Enum("success", "warning", "error", name="state"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event")
    # ### end Alembic commands ###
