"""Distributor null in film week.

Revision ID: d96ab19acb14
Revises: 3e1d353cf71e
Create Date: 2023-04-17 20:38:17.137993

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d96ab19acb14"
down_revision = "3e1d353cf71e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "film_week",
        "distributor_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "film_week",
        "distributor_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    # ### end Alembic commands ###
