"""Del country id

Revision ID: 202f40c2cd3c
Revises: 72b8189269ab
Create Date: 2023-07-30 14:39:39.932337

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "202f40c2cd3c"
down_revision = "72b8189269ab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("film_country_id_fkey", "film", type_="foreignkey")
    op.drop_column("film", "country_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "film",
        sa.Column(
            "country_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        "film_country_id_fkey", "film", "country", ["country_id"], ["id"]
    )
    # ### end Alembic commands ###
