"""Add dist market share

Revision ID: 3661a8e9d4fa
Revises: d3ebee3d9ad2
Create Date: 2023-07-26 18:42:56.243651

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3661a8e9d4fa"
down_revision = "d3ebee3d9ad2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "distributor_market_share",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("distributor_id", sa.Integer(), nullable=False),
        sa.Column("market_share", sa.Float(), nullable=False),
        sa.Column("gross", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["distributor_id"],
            ["distributor.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("distributor_market_share")
    # ### end Alembic commands ###
