"""Add country of origin

Revision ID: 554e67af6ddf
Revises: fdac9f9ef28d
Create Date: 2023-08-01 19:44:22.178312

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "554e67af6ddf"
down_revision = "fdac9f9ef28d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "film", sa.Column("country_of_origin_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "film", "country", ["country_of_origin_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "film", type_="foreignkey")
    op.drop_column("film", "country_of_origin_id")
    # ### end Alembic commands ###
