"""Add country market share

Revision ID: 72b8189269ab
Revises: a1b21f981432
Create Date: 2023-07-30 13:54:38.763473

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "72b8189269ab"
down_revision = "a1b21f981432"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "country_market_share",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("country_id", sa.Integer(), nullable=False),
        sa.Column("market_share", sa.Float(), nullable=False),
        sa.Column("gross", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["country.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("country_id", "year"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("country_market_share")
    # ### end Alembic commands ###
