"""Add country groups

Revision ID: 7717cd775d13
Revises: d08b41311774
Create Date: 2023-07-31 19:47:47.402405

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7717cd775d13"
down_revision = "d08b41311774"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "country_group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "country_group_countries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("country_group_id", sa.Integer(), nullable=False),
        sa.Column("country_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["country_group_id"],
            ["country_group.id"],
        ),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["country.id"],
        ),
        sa.PrimaryKeyConstraint("id", "country_group_id", "country_id"),
    )
    op.create_table(
        "country_group_market_share",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("country_group_id", sa.Integer(), nullable=False),
        sa.Column("market_share", sa.Float(), nullable=False),
        sa.Column("gross", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["country_group_id"],
            ["country_group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("country_group_id", "year"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("country_group_market_share")
    op.drop_table("country_group_countries")
    op.drop_table("country_group")
    # ### end Alembic commands ###
