"""Distributor m2m

Revision ID: 7ea7616eadf5
Revises: d96ab19acb14
Create Date: 2023-07-16 18:46:36.140907

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7ea7616eadf5"
down_revision = "d96ab19acb14"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "distributors",
        sa.Column("film_id", sa.Integer(), nullable=False),
        sa.Column("distributor_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["distributor_id"],
            ["distributor.id"],
        ),
        sa.ForeignKeyConstraint(
            ["film_id"],
            ["film.id"],
        ),
        sa.PrimaryKeyConstraint("film_id", "distributor_id"),
    )
    op.drop_constraint("film_distributor_id_fkey", "film", type_="foreignkey")
    op.drop_column("film", "distributor_id")
    op.drop_constraint(
        "film_week_distributor_id_fkey", "film_week", type_="foreignkey"
    )
    op.drop_column("film_week", "distributor_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "film_week",
        sa.Column(
            "distributor_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        "film_week_distributor_id_fkey",
        "film_week",
        "distributor",
        ["distributor_id"],
        ["id"],
    )
    op.add_column(
        "film",
        sa.Column(
            "distributor_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        "film_distributor_id_fkey",
        "film",
        "distributor",
        ["distributor_id"],
        ["id"],
    )
    op.drop_table("distributors")
    # ### end Alembic commands ###
