"""Del country id

Revision ID: d08b41311774
Revises: a1b21f981432
Create Date: 2023-07-30 20:27:36.624447

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d08b41311774"
down_revision = "a1b21f981432"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("film_country_id_fkey", "film", type_="foreignkey")
    op.drop_column("film", "country_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "film",
        sa.Column(
            "country_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        "film_country_id_fkey", "film", "country", ["country_id"], ["id"]
    )
    # ### end Alembic commands ###
