"""Add FW date index

Revision ID: d3ebee3d9ad2
Revises: 7ea7616eadf5
Create Date: 2023-07-25 17:42:15.818486

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d3ebee3d9ad2"
down_revision = "7ea7616eadf5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_film_week_date"), "film_week", ["date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_film_week_date"), table_name="film_week")
    # ### end Alembic commands ###
