name: Continuous Integration and Delivery

on:
  push:
    branches:
      - beta

jobs:
  stage:
    name: Deploy to beta.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout staging
        uses: actions/checkout@v1
      - name: Add the private SSH key to the ssh-agent
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-add - <<< "${{ secrets.PRIVATE_KEY }}"

      - name: Setup node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: './src/sophronia/package-lock.json'

      - name: Install
        run: npm ci --prefix ./src/sophronia/

      - name: Build React
        env:
          NEXT_PUBLIC_BACKEND_URL: https://api.boxofficedata.co.uk/api/
        run: CI=false npm run build --prefix ./src/sophronia/

      - name: Deploy on VM
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          scp  -o StrictHostKeyChecking=no -r ./src/sophronia/package.json package-lock.json root@${{ secrets.STAGING_IP_ADDRESS }}:/var/www/uk-box-office-beta/src/sophronia/
          scp  -o StrictHostKeyChecking=no -r ./src/sophronia/.next/* root@${{ secrets.STAGING_IP_ADDRESS }}:/var/www/uk-box-office-beta/src/sophronia/.next/*
          ssh -o StrictHostKeyChecking=no root@${{ secrets.STAGING_IP_ADDRESS }} << 'ENDSSH'
            cd /var/www/uk-box-office-beta/src/sophronia
            npm install
            systemctl restart nginx
          ENDSSH
