name: Build frontend

on:
  pull_request:


jobs:
  stage:
    name: Build frontend.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout staging
        uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: './src/sophronia/package-lock.json'

      - name: Install
        run: npm ci --prefix ./src/sophronia/

      - name: Build React
        env:
          NEXT_PUBLIC_BACKEND_URL: https://api.boxofficedata.co.uk/api/
        run: CI=false npm run build --prefix ./src/sophronia/
