name: Continuous Integration and Delivery

on:
  push:
    branches:
      - main

jobs:
  stage:
    name: Deploy to production.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout staging
        uses: actions/checkout@v1
      - name: Add the private SSH key to the ssh-agent
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-add - <<< "${{ secrets.PRIVATE_KEY }}"

      - name: Deploy on VM
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          scp  -o StrictHostKeyChecking=no -r ./src/backend/* root@${{ secrets.STAGING_IP_ADDRESS }}:/var/www/uk-box-office/src/backend/
          ssh -o StrictHostKeyChecking=no root@${{ secrets.STAGING_IP_ADDRESS }} << 'ENDSSH'
            cd /var/www/uk-box-office
            source venv/bin/activate
            cd src/backend
            pip install -r requirements.txt
            flask db upgrade
            systemctl restart nginx
            systemctl restart gunicorn
          ENDSSH
