name: Pytest

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/berenice/requirements.txt
      - name: Test with pytest
        run: |
          cd src/berenice && pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=ukbo tests/ | tee pytest-coverage.txt
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./src/berenice/pytest-coverage.txt
          junitxml-path: ./src/berenice/pytest.xml
